package org.leetcodelikeplatform.entities;

import lombok.Getter;
import lombok.Setter;
import org.leetcodelikeplatform.enums.DifficultyLevel;

import java.util.Objects;

@Getter
@Setter
public class Contest {
    private static  int autoGeneratedId = 0;
    private int id;
    private String name;
    private DifficultyLevel difficultyLevel;
    private User creator;

    public Contest(String name, DifficultyLevel difficultyLevel, User creator) {
        this.id = ++autoGeneratedId;
        this.name = name;
        this.difficultyLevel = difficultyLevel;
        this.creator = creator;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Contest contest = (Contest) o;
        return id == contest.id;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
