package org.leetcodelikeplatform.entities;

import lombok.*;
import org.leetcodelikeplatform.enums.DifficultyLevel;

import java.util.Objects;

@Getter
@Setter
@ToString
public class Question {
    private static int autoGeneratedId= 0;
    private int id;
    private DifficultyLevel difficultyLevel;
    int score;

    public Question(DifficultyLevel difficultyLevel, int score) {
        this.id = ++autoGeneratedId;
        this.difficultyLevel = difficultyLevel;
        this.score = score;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Question question = (Question) o;
        return id == question.id;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
